from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Mix(PseudoUGen):
    @classmethod
    def new(cls, sources) -> Any: ...
    @classmethod
    def multichannel(cls, sources, channel_count) -> Any: ...

class MulAdd(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., multiplier: UGenScalarInput = ..., addend: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def multiplier(self) -> UGenScalar: ...
    @property
    def addend(self) -> UGenScalar: ...
    @classmethod
    def new(cls, *, source: UGenRecursiveInput = ..., multiplier: UGenRecursiveInput = ..., addend: UGenRecursiveInput = ...) -> UGenOperable: ...

class Sum3(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, input_one: UGenScalarInput = ..., input_two: UGenScalarInput = ..., input_three: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def input_one(self) -> UGenScalar: ...
    @property
    def input_two(self) -> UGenScalar: ...
    @property
    def input_three(self) -> UGenScalar: ...
    @classmethod
    def new(cls, *, input_one: UGenRecursiveInput = ..., input_two: UGenRecursiveInput = ..., input_three: UGenRecursiveInput = ...) -> UGenOperable: ...

class Sum4(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, input_one: UGenScalarInput = ..., input_two: UGenScalarInput = ..., input_three: UGenScalarInput = ..., input_four: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def input_one(self) -> UGenScalar: ...
    @property
    def input_two(self) -> UGenScalar: ...
    @property
    def input_three(self) -> UGenScalar: ...
    @property
    def input_four(self) -> UGenScalar: ...
    @classmethod
    def new(cls, *, input_one: UGenRecursiveInput = ..., input_two: UGenRecursiveInput = ..., input_three: UGenRecursiveInput = ..., input_four: UGenRecursiveInput = ...) -> UGenOperable: ...
