from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class BAllPass(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class BBandPass(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., bandwidth: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def bandwidth(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., bandwidth: UGenRecursiveInput = ...) -> UGenOperable: ...

class BBandStop(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., bandwidth: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def bandwidth(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., bandwidth: UGenRecursiveInput = ...) -> UGenOperable: ...

class BHiCut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., order: UGenScalarInput = ..., max_order: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def order(self) -> UGenScalar: ...
    @property
    def max_order(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., order: UGenRecursiveInput = ..., max_order: UGenRecursiveInput = ...) -> UGenOperable: ...

class BHiPass(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class BHiShelf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_s: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_s(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_s: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...

class BLowCut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., order: UGenScalarInput = ..., max_order: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def order(self) -> UGenScalar: ...
    @property
    def max_order(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., order: UGenRecursiveInput = ..., max_order: UGenRecursiveInput = ...) -> UGenOperable: ...

class BLowPass(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class BLowShelf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_s: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_s(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_s: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...

class BPeakEQ(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...
