from typing import Any
from ..enums import DoneAction, CalculationRate
from ..typing import Default, CalculationRateLike, DEFAULT
from .core import UGenVector, UGenScalar, UGenScalarInput, ugen, param, UGenVectorInput, UGenOperable, UGenRecursiveInput, UGen
class BufRd(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, buffer_id: UGenScalarInput = ..., phase: UGenScalarInput = ..., loop: UGenScalarInput = ..., interpolation: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @property
    def interpolation(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., interpolation: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., interpolation: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class BufWr(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., phase: UGenScalarInput = ..., loop: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class ClearBuf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class LocalBuf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: UGenScalarInput = ..., frame_count: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def channel_count(self) -> UGenScalar: ...
    @property
    def frame_count(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, channel_count: UGenRecursiveInput = ..., frame_count: UGenRecursiveInput = ...) -> UGenOperable: ...

class MaxLocalBufs(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class PlayBuf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, buffer_id: UGenScalarInput = ..., rate: UGenScalarInput = ..., trigger: UGenScalarInput = ..., start_position: UGenScalarInput = ..., loop: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def rate(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def start_position(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., start_position: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., start_position: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class RecordBuf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., offset: UGenScalarInput = ..., record_level: UGenScalarInput = ..., preexisting_level: UGenScalarInput = ..., run: UGenScalarInput = ..., loop: UGenScalarInput = ..., trigger: UGenScalarInput = ..., done_action: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def offset(self) -> UGenScalar: ...
    @property
    def record_level(self) -> UGenScalar: ...
    @property
    def preexisting_level(self) -> UGenScalar: ...
    @property
    def run(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., offset: UGenRecursiveInput = ..., record_level: UGenRecursiveInput = ..., preexisting_level: UGenRecursiveInput = ..., run: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., offset: UGenRecursiveInput = ..., record_level: UGenRecursiveInput = ..., preexisting_level: UGenRecursiveInput = ..., run: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class ScopeOut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class ScopeOut2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, scope_id: UGenScalarInput = ..., max_frames: UGenScalarInput = ..., scope_frames: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def scope_id(self) -> UGenScalar: ...
    @property
    def max_frames(self) -> UGenScalar: ...
    @property
    def scope_frames(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, scope_id: UGenRecursiveInput = ..., max_frames: UGenRecursiveInput = ..., scope_frames: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, scope_id: UGenRecursiveInput = ..., max_frames: UGenRecursiveInput = ..., scope_frames: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
