from typing import Any

from ..typing import CalculationRateLike
from .core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, param, ugen

class CuspL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class CuspN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class FBSineC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., im: UGenScalarInput = ..., fb: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def im(self) -> UGenScalar: ...
    @property
    def fb(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., im: UGenRecursiveInput = ..., fb: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class FBSineL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., im: UGenScalarInput = ..., fb: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def im(self) -> UGenScalar: ...
    @property
    def fb(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., im: UGenRecursiveInput = ..., fb: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class FBSineN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., im: UGenScalarInput = ..., fb: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def im(self) -> UGenScalar: ...
    @property
    def fb(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., im: UGenRecursiveInput = ..., fb: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class GbmanL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class GbmanN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class HenonC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., x_0: UGenScalarInput = ..., x_1: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def x_0(self) -> UGenScalar: ...
    @property
    def x_1(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., x_0: UGenRecursiveInput = ..., x_1: UGenRecursiveInput = ...) -> UGenOperable: ...

class HenonL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., x_0: UGenScalarInput = ..., x_1: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def x_0(self) -> UGenScalar: ...
    @property
    def x_1(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., x_0: UGenRecursiveInput = ..., x_1: UGenRecursiveInput = ...) -> UGenOperable: ...

class HenonN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., x_0: UGenScalarInput = ..., x_1: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def x_0(self) -> UGenScalar: ...
    @property
    def x_1(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., x_0: UGenRecursiveInput = ..., x_1: UGenRecursiveInput = ...) -> UGenOperable: ...

class LatoocarfianC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., c: UGenScalarInput = ..., d: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def d(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., d: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class LatoocarfianL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., c: UGenScalarInput = ..., d: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def d(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., d: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class LatoocarfianN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., c: UGenScalarInput = ..., d: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def d(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., d: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class LinCongC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., m: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def m(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., m: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class LinCongL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., m: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def m(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., m: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class LinCongN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., m: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def m(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., m: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class LorenzL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., s: UGenScalarInput = ..., r: UGenScalarInput = ..., b: UGenScalarInput = ..., h: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., zi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def s(self) -> UGenScalar: ...
    @property
    def r(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def h(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @property
    def zi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., s: UGenRecursiveInput = ..., r: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., h: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ..., zi: UGenRecursiveInput = ...) -> UGenOperable: ...

class QuadC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., c: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class QuadL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., c: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class QuadN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., a: UGenScalarInput = ..., b: UGenScalarInput = ..., c: UGenScalarInput = ..., xi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ..., c: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ...) -> UGenOperable: ...

class StandardL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., k: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def k(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., k: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...

class StandardN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., k: UGenScalarInput = ..., xi: UGenScalarInput = ..., yi: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def k(self) -> UGenScalar: ...
    @property
    def xi(self) -> UGenScalar: ...
    @property
    def yi(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., k: UGenRecursiveInput = ..., xi: UGenRecursiveInput = ..., yi: UGenRecursiveInput = ...) -> UGenOperable: ...
