from .core import UGenScalar, UGenScalarInput, ugen, param, UGenOperable, UGenRecursiveInput, UGen
from ..typing import CalculationRateLike
from typing import Any
class Convolution(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., kernel: UGenScalarInput = ..., framesize: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def kernel(self) -> UGenScalar: ...
    @property
    def framesize(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., kernel: UGenRecursiveInput = ..., framesize: UGenRecursiveInput = ...) -> UGenOperable: ...

class Convolution2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., kernel: UGenScalarInput = ..., trigger: UGenScalarInput = ..., framesize: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def kernel(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def framesize(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., kernel: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., framesize: UGenRecursiveInput = ...) -> UGenOperable: ...

class Convolution2L(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., kernel: UGenScalarInput = ..., trigger: UGenScalarInput = ..., framesize: UGenScalarInput = ..., crossfade: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def kernel(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def framesize(self) -> UGenScalar: ...
    @property
    def crossfade(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., kernel: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., framesize: UGenRecursiveInput = ..., crossfade: UGenRecursiveInput = ...) -> UGenOperable: ...

class Convolution3(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., kernel: UGenScalarInput = ..., trigger: UGenScalarInput = ..., framesize: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def kernel(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def framesize(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., kernel: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., framesize: UGenRecursiveInput = ...) -> UGenOperable: ...
