from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class AllpassC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class AllpassL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class AllpassN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufAllpassC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufAllpassL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufAllpassN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufCombC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufCombL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufCombN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufDelayC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufDelayL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufDelayN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class CombC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class CombL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class CombN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class DelTapRd(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., phase: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., interpolation: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def interpolation(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., interpolation: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., interpolation: UGenRecursiveInput = ...) -> UGenOperable: ...

class DelTapWr(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class DelayC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class DelayL(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class DelayN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Delay1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Delay2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
