from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Dbrown(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., step: UGenScalarInput = ..., length: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def step(self) -> UGenScalar: ...
    @property
    def length(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., step: UGenRecursiveInput = ..., length: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dbufrd(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., phase: UGenScalarInput = ..., loop: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dbufwr(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., buffer_id: UGenScalarInput = ..., phase: UGenScalarInput = ..., loop: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, source: UGenRecursiveInput = ..., buffer_id: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ...) -> UGenOperable: ...

class Demand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., reset: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def reset(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class DemandEnvGen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, level: UGenScalarInput = ..., duration: UGenScalarInput = ..., shape: UGenScalarInput = ..., curve: UGenScalarInput = ..., gate: UGenScalarInput = ..., reset: UGenScalarInput = ..., level_scale: UGenScalarInput = ..., level_bias: UGenScalarInput = ..., time_scale: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def level(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def shape(self) -> UGenScalar: ...
    @property
    def curve(self) -> UGenScalar: ...
    @property
    def gate(self) -> UGenScalar: ...
    @property
    def reset(self) -> UGenScalar: ...
    @property
    def level_scale(self) -> UGenScalar: ...
    @property
    def level_bias(self) -> UGenScalar: ...
    @property
    def time_scale(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, level: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., shape: UGenRecursiveInput = ..., curve: UGenRecursiveInput = ..., gate: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ..., level_scale: UGenRecursiveInput = ..., level_bias: UGenRecursiveInput = ..., time_scale: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, level: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., shape: UGenRecursiveInput = ..., curve: UGenRecursiveInput = ..., gate: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ..., level_scale: UGenRecursiveInput = ..., level_bias: UGenRecursiveInput = ..., time_scale: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dgeom(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, start: UGenScalarInput = ..., grow: UGenScalarInput = ..., length: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def start(self) -> UGenScalar: ...
    @property
    def grow(self) -> UGenScalar: ...
    @property
    def length(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, start: UGenRecursiveInput = ..., grow: UGenRecursiveInput = ..., length: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dibrown(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., step: UGenScalarInput = ..., length: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def step(self) -> UGenScalar: ...
    @property
    def length(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., step: UGenRecursiveInput = ..., length: UGenRecursiveInput = ...) -> UGenOperable: ...

class Diwhite(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., length: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def length(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., length: UGenRecursiveInput = ...) -> UGenOperable: ...

class Drand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, repeats: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def repeats(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, repeats: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dreset(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., reset: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def reset(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, source: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dseq(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, repeats: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def repeats(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, repeats: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dser(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, repeats: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def repeats(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, repeats: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dseries(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, length: UGenScalarInput = ..., start: UGenScalarInput = ..., step: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def length(self) -> UGenScalar: ...
    @property
    def start(self) -> UGenScalar: ...
    @property
    def step(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, length: UGenRecursiveInput = ..., start: UGenRecursiveInput = ..., step: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dshuf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, repeats: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def repeats(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, repeats: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dstutter(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, n: UGenScalarInput = ..., source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def n(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, n: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dswitch(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, index_: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def index_(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, index_: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dswitch1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, index_: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def index_(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, index_: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dunique(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., max_buffer_size: UGenScalarInput = ..., protected: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def max_buffer_size(self) -> UGenScalar: ...
    @property
    def protected(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, source: UGenRecursiveInput = ..., max_buffer_size: UGenRecursiveInput = ..., protected: UGenRecursiveInput = ...) -> UGenOperable: ...

class Duty(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, duration: UGenScalarInput = ..., reset: UGenScalarInput = ..., level: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def reset(self) -> UGenScalar: ...
    @property
    def level(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, duration: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ..., level: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, duration: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ..., level: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dwhite(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., length: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def length(self) -> UGenScalar: ...
    @classmethod
    def dr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., length: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dwrand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, repeats: UGenScalarInput = ..., length: UGenScalarInput = ..., weights: UGenVectorInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def repeats(self) -> UGenScalar: ...
    @property
    def length(self) -> UGenScalar: ...
    @property
    def weights(self) -> UGenVector: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, repeats: UGenRecursiveInput = ..., length: UGenRecursiveInput = ..., weights: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dxrand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, repeats: UGenScalarInput = ..., sequence: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def repeats(self) -> UGenScalar: ...
    @property
    def sequence(self) -> UGenVector: ...
    @classmethod
    def dr(cls, *, repeats: UGenRecursiveInput = ..., sequence: UGenRecursiveInput = ...) -> UGenOperable: ...
