from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class DiskIn(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, buffer_id: UGenScalarInput = ..., loop: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class DiskOut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class VDiskIn(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, buffer_id: UGenScalarInput = ..., rate: UGenScalarInput = ..., loop: UGenScalarInput = ..., send_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def rate(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @property
    def send_id(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., send_id: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
