from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class CompanderD(PseudoUGen):
    @classmethod
    def ar(cls, source = None, threshold = 0.5, clamp_time = 0.01, relax_time = 0.1, slope_above = 1.0, slope_below = 1.0) -> Any: ...

class Amplitude(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., attack_time: UGenScalarInput = ..., release_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def attack_time(self) -> UGenScalar: ...
    @property
    def release_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., release_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., release_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Compander(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., control: UGenScalarInput = ..., threshold: UGenScalarInput = ..., slope_below: UGenScalarInput = ..., slope_above: UGenScalarInput = ..., clamp_time: UGenScalarInput = ..., relax_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def control(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @property
    def slope_below(self) -> UGenScalar: ...
    @property
    def slope_above(self) -> UGenScalar: ...
    @property
    def clamp_time(self) -> UGenScalar: ...
    @property
    def relax_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., control: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ..., slope_below: UGenRecursiveInput = ..., slope_above: UGenRecursiveInput = ..., clamp_time: UGenRecursiveInput = ..., relax_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Limiter(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., level: UGenScalarInput = ..., duration: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def level(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., level: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...

class Normalizer(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., level: UGenScalarInput = ..., duration: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def level(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., level: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...
