from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Envelope:
    def __init__(self, amplitudes: Sequence[UGenOperable | float] = (0, 1, 0), durations: Sequence[UGenOperable | float] = (1, 1), curves: Sequence[EnvelopeShape | UGenOperable | float | str | None] = (EnvelopeShape.LINEAR, EnvelopeShape.LINEAR), release_node: int | None = None, loop_node: int | None = None, offset: UGenOperable | float = 0.0) -> None: ...
    def __plot__(self) -> tuple['numpy.ndarray', float]: ...
    @classmethod
    def adsr(cls, attack_time = 0.01, decay_time = 0.3, sustain = 0.5, release_time = 1.0, peak = 1.0, curve = -4.0, bias = 0.0) -> 'Envelope': ...
    @classmethod
    def asr(cls, attack_time = 0.01, sustain = 1.0, release_time = 1.0, curve = -4.0) -> 'Envelope': ...
    def at(self, time: float) -> float: ...
    @classmethod
    def from_segments(cls, initial_amplitude = 0, segments = None, release_node = None, loop_node = None, offset = None) -> 'Envelope': ...
    @classmethod
    def percussive(cls, attack_time: UGenOperable | float = 0.01, release_time: UGenOperable | float = 1.0, amplitude: UGenOperable | float = 1.0, curve: EnvelopeShape | UGenOperable | float | str = -4.0) -> 'Envelope': ...
    @classmethod
    def linen(cls, attack_time = 0.01, sustain_time = 1.0, release_time = 1.0, level = 1.0, curve = 1) -> 'Envelope': ...
    def serialize(self, **kwargs) -> UGenVector: ...
    def serialize_interpolated(self) -> UGenVector: ...
    def to_array(self, length: int = 1024) -> list[float]: ...
    @classmethod
    def triangle(cls, duration = 1.0, amplitude = 1.0) -> 'Envelope': ...
    @property
    def amplitudes(self) -> tuple[UGenOperable | float]: ...
    @property
    def curves(self) -> tuple[EnvelopeShape | UGenOperable | float]: ...
    @property
    def duration(self) -> UGenOperable | float: ...
    @property
    def durations(self) -> tuple[UGenOperable | float]: ...
    @property
    def envelope_segments(self) -> Any: ...
    @property
    def initial_amplitude(self) -> UGenOperable | float: ...
    @property
    def loop_node(self) -> int | None: ...
    @property
    def offset(self) -> UGenOperable | float: ...
    @property
    def release_node(self) -> int | None: ...

class Done(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class EnvGen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, gate: UGenScalarInput = ..., level_scale: UGenScalarInput = ..., level_bias: UGenScalarInput = ..., time_scale: UGenScalarInput = ..., done_action: UGenScalarInput = ..., envelope: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def gate(self) -> UGenScalar: ...
    @property
    def level_scale(self) -> UGenScalar: ...
    @property
    def level_bias(self) -> UGenScalar: ...
    @property
    def time_scale(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @property
    def envelope(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, gate: UGenRecursiveInput = ..., level_scale: UGenRecursiveInput = ..., level_bias: UGenRecursiveInput = ..., time_scale: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., envelope: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, gate: UGenRecursiveInput = ..., level_scale: UGenRecursiveInput = ..., level_bias: UGenRecursiveInput = ..., time_scale: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., envelope: UGenRecursiveInput = ...) -> UGenOperable: ...

class Free(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., node_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def node_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., node_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class FreeSelf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class FreeSelfWhenDone(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Linen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, gate: UGenScalarInput = ..., attack_time: UGenScalarInput = ..., sustain_level: UGenScalarInput = ..., release_time: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def gate(self) -> UGenScalar: ...
    @property
    def attack_time(self) -> UGenScalar: ...
    @property
    def sustain_level(self) -> UGenScalar: ...
    @property
    def release_time(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, gate: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., sustain_level: UGenRecursiveInput = ..., release_time: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class Pause(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., node_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def node_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., node_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class PauseSelf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PauseSelfWhenDone(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
