from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Done(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class EnvGen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, gate: UGenScalarInput = ..., level_scale: UGenScalarInput = ..., level_bias: UGenScalarInput = ..., time_scale: UGenScalarInput = ..., done_action: UGenScalarInput = ..., envelope: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def gate(self) -> UGenScalar: ...
    @property
    def level_scale(self) -> UGenScalar: ...
    @property
    def level_bias(self) -> UGenScalar: ...
    @property
    def time_scale(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @property
    def envelope(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, gate: UGenRecursiveInput = ..., level_scale: UGenRecursiveInput = ..., level_bias: UGenRecursiveInput = ..., time_scale: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., envelope: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, gate: UGenRecursiveInput = ..., level_scale: UGenRecursiveInput = ..., level_bias: UGenRecursiveInput = ..., time_scale: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ..., envelope: UGenRecursiveInput = ...) -> UGenOperable: ...

class Free(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., node_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def node_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., node_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class FreeSelf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class FreeSelfWhenDone(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Linen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, gate: UGenScalarInput = ..., attack_time: UGenScalarInput = ..., sustain_level: UGenScalarInput = ..., release_time: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def gate(self) -> UGenScalar: ...
    @property
    def attack_time(self) -> UGenScalar: ...
    @property
    def sustain_level(self) -> UGenScalar: ...
    @property
    def release_time(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, gate: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., sustain_level: UGenRecursiveInput = ..., release_time: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class Pause(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., node_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def node_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., node_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class PauseSelf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PauseSelfWhenDone(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
