from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Blip(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., harmonic_count: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def harmonic_count(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., harmonic_count: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., harmonic_count: UGenRecursiveInput = ...) -> UGenOperable: ...

class FSinOsc(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class Klank(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency_scale: UGenScalarInput = ..., frequency_offset: UGenScalarInput = ..., decay_scale: UGenScalarInput = ..., specifications: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency_scale(self) -> UGenScalar: ...
    @property
    def frequency_offset(self) -> UGenScalar: ...
    @property
    def decay_scale(self) -> UGenScalar: ...
    @property
    def specifications(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency_scale: UGenRecursiveInput = ..., frequency_offset: UGenRecursiveInput = ..., decay_scale: UGenRecursiveInput = ..., specifications: UGenRecursiveInput = ...) -> UGenOperable: ...

class Pulse(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., width: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...

class Saw(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
