from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Changed(PseudoUGen):
    @classmethod
    def ar(cls, source, threshold = 0) -> UGenOperable: ...
    @classmethod
    def kr(cls, source, threshold = 0) -> UGenOperable: ...

class APF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., radius: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def radius(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., radius: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., radius: UGenRecursiveInput = ...) -> UGenOperable: ...

class BPF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class BPZ2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class BRF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class BRZ2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Decay(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Decay2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., attack_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def attack_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class DetectSilence(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., threshold: UGenScalarInput = ..., time: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @property
    def time(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ..., time: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ..., time: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class FOS(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., a_0: UGenScalarInput = ..., a_1: UGenScalarInput = ..., b_1: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def a_0(self) -> UGenScalar: ...
    @property
    def a_1(self) -> UGenScalar: ...
    @property
    def b_1(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., a_0: UGenRecursiveInput = ..., a_1: UGenRecursiveInput = ..., b_1: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., a_0: UGenRecursiveInput = ..., a_1: UGenRecursiveInput = ..., b_1: UGenRecursiveInput = ...) -> UGenOperable: ...

class Formlet(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., attack_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def attack_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., attack_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class HPF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class HPZ1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class HPZ2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Integrator(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., coefficient: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def coefficient(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...

class Lag(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class LagUD(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time_up: UGenScalarInput = ..., lag_time_down: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time_up(self) -> UGenScalar: ...
    @property
    def lag_time_down(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time_up: UGenRecursiveInput = ..., lag_time_down: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time_up: UGenRecursiveInput = ..., lag_time_down: UGenRecursiveInput = ...) -> UGenOperable: ...

class Lag2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Lag2UD(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time_up: UGenScalarInput = ..., lag_time_down: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time_up(self) -> UGenScalar: ...
    @property
    def lag_time_down(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time_up: UGenRecursiveInput = ..., lag_time_down: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time_up: UGenRecursiveInput = ..., lag_time_down: UGenRecursiveInput = ...) -> UGenOperable: ...

class Lag3(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Lag3UD(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time_up: UGenScalarInput = ..., lag_time_down: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time_up(self) -> UGenScalar: ...
    @property
    def lag_time_down(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time_up: UGenRecursiveInput = ..., lag_time_down: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time_up: UGenRecursiveInput = ..., lag_time_down: UGenRecursiveInput = ...) -> UGenOperable: ...

class LeakDC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., coefficient: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def coefficient(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...

class LPF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LPZ1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class LPZ2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Median(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, length: UGenScalarInput = ..., source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def length(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, length: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, length: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class MidEQ(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., db: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @property
    def db(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ..., db: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ..., db: UGenRecursiveInput = ...) -> UGenOperable: ...

class MoogFF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., gain: UGenScalarInput = ..., reset: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @property
    def reset(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ..., reset: UGenRecursiveInput = ...) -> UGenOperable: ...

class OnePole(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., coefficient: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def coefficient(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...

class OneZero(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., coefficient: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def coefficient(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...

class RHPF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class RLPF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., reciprocal_of_q: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def reciprocal_of_q(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., reciprocal_of_q: UGenRecursiveInput = ...) -> UGenOperable: ...

class Ramp(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., lag_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def lag_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., lag_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class Ringz(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ...) -> UGenOperable: ...

class SOS(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., a_0: UGenScalarInput = ..., a_1: UGenScalarInput = ..., a_2: UGenScalarInput = ..., b_1: UGenScalarInput = ..., b_2: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def a_0(self) -> UGenScalar: ...
    @property
    def a_1(self) -> UGenScalar: ...
    @property
    def a_2(self) -> UGenScalar: ...
    @property
    def b_1(self) -> UGenScalar: ...
    @property
    def b_2(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., a_0: UGenRecursiveInput = ..., a_1: UGenRecursiveInput = ..., a_2: UGenRecursiveInput = ..., b_1: UGenRecursiveInput = ..., b_2: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., a_0: UGenRecursiveInput = ..., a_1: UGenRecursiveInput = ..., a_2: UGenRecursiveInput = ..., b_1: UGenRecursiveInput = ..., b_2: UGenRecursiveInput = ...) -> UGenOperable: ...

class Slew(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., up: UGenScalarInput = ..., down: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def up(self) -> UGenScalar: ...
    @property
    def down(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., up: UGenRecursiveInput = ..., down: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., up: UGenRecursiveInput = ..., down: UGenRecursiveInput = ...) -> UGenOperable: ...

class Slope(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class TwoPole(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., radius: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def radius(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., radius: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., radius: UGenRecursiveInput = ...) -> UGenOperable: ...

class TwoZero(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., radius: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def radius(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., radius: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., radius: UGenRecursiveInput = ...) -> UGenOperable: ...
