from typing import Any

from ..enums import CalculationRate
from ..typing import CalculationRateLike, Default
from .core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, param, ugen

class Gendy1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, ampdist: UGenScalarInput = ..., durdist: UGenScalarInput = ..., adparam: UGenScalarInput = ..., ddparam: UGenScalarInput = ..., minfrequency: UGenScalarInput = ..., maxfrequency: UGenScalarInput = ..., ampscale: UGenScalarInput = ..., durscale: UGenScalarInput = ..., init_cps: UGenScalarInput = ..., knum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def ampdist(self) -> UGenScalar: ...
    @property
    def durdist(self) -> UGenScalar: ...
    @property
    def adparam(self) -> UGenScalar: ...
    @property
    def ddparam(self) -> UGenScalar: ...
    @property
    def minfrequency(self) -> UGenScalar: ...
    @property
    def maxfrequency(self) -> UGenScalar: ...
    @property
    def ampscale(self) -> UGenScalar: ...
    @property
    def durscale(self) -> UGenScalar: ...
    @property
    def init_cps(self) -> UGenScalar: ...
    @property
    def knum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, ampdist: UGenRecursiveInput = ..., durdist: UGenRecursiveInput = ..., adparam: UGenRecursiveInput = ..., ddparam: UGenRecursiveInput = ..., minfrequency: UGenRecursiveInput = ..., maxfrequency: UGenRecursiveInput = ..., ampscale: UGenRecursiveInput = ..., durscale: UGenRecursiveInput = ..., init_cps: UGenRecursiveInput = ..., knum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, ampdist: UGenRecursiveInput = ..., durdist: UGenRecursiveInput = ..., adparam: UGenRecursiveInput = ..., ddparam: UGenRecursiveInput = ..., minfrequency: UGenRecursiveInput = ..., maxfrequency: UGenRecursiveInput = ..., ampscale: UGenRecursiveInput = ..., durscale: UGenRecursiveInput = ..., init_cps: UGenRecursiveInput = ..., knum: UGenRecursiveInput = ...) -> UGenOperable: ...

class Gendy2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, ampdist: UGenScalarInput = ..., durdist: UGenScalarInput = ..., adparam: UGenScalarInput = ..., ddparam: UGenScalarInput = ..., minfrequency: UGenScalarInput = ..., maxfrequency: UGenScalarInput = ..., ampscale: UGenScalarInput = ..., durscale: UGenScalarInput = ..., init_cps: UGenScalarInput = ..., knum: UGenScalarInput = ..., a: UGenScalarInput = ..., c: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def ampdist(self) -> UGenScalar: ...
    @property
    def durdist(self) -> UGenScalar: ...
    @property
    def adparam(self) -> UGenScalar: ...
    @property
    def ddparam(self) -> UGenScalar: ...
    @property
    def minfrequency(self) -> UGenScalar: ...
    @property
    def maxfrequency(self) -> UGenScalar: ...
    @property
    def ampscale(self) -> UGenScalar: ...
    @property
    def durscale(self) -> UGenScalar: ...
    @property
    def init_cps(self) -> UGenScalar: ...
    @property
    def knum(self) -> UGenScalar: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def c(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, ampdist: UGenRecursiveInput = ..., durdist: UGenRecursiveInput = ..., adparam: UGenRecursiveInput = ..., ddparam: UGenRecursiveInput = ..., minfrequency: UGenRecursiveInput = ..., maxfrequency: UGenRecursiveInput = ..., ampscale: UGenRecursiveInput = ..., durscale: UGenRecursiveInput = ..., init_cps: UGenRecursiveInput = ..., knum: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, ampdist: UGenRecursiveInput = ..., durdist: UGenRecursiveInput = ..., adparam: UGenRecursiveInput = ..., ddparam: UGenRecursiveInput = ..., minfrequency: UGenRecursiveInput = ..., maxfrequency: UGenRecursiveInput = ..., ampscale: UGenRecursiveInput = ..., durscale: UGenRecursiveInput = ..., init_cps: UGenRecursiveInput = ..., knum: UGenRecursiveInput = ..., a: UGenRecursiveInput = ..., c: UGenRecursiveInput = ...) -> UGenOperable: ...

class Gendy3(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, ampdist: UGenScalarInput = ..., durdist: UGenScalarInput = ..., adparam: UGenScalarInput = ..., ddparam: UGenScalarInput = ..., frequency: UGenScalarInput = ..., ampscale: UGenScalarInput = ..., durscale: UGenScalarInput = ..., init_cps: UGenScalarInput = ..., knum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def ampdist(self) -> UGenScalar: ...
    @property
    def durdist(self) -> UGenScalar: ...
    @property
    def adparam(self) -> UGenScalar: ...
    @property
    def ddparam(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def ampscale(self) -> UGenScalar: ...
    @property
    def durscale(self) -> UGenScalar: ...
    @property
    def init_cps(self) -> UGenScalar: ...
    @property
    def knum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, ampdist: UGenRecursiveInput = ..., durdist: UGenRecursiveInput = ..., adparam: UGenRecursiveInput = ..., ddparam: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., ampscale: UGenRecursiveInput = ..., durscale: UGenRecursiveInput = ..., init_cps: UGenRecursiveInput = ..., knum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, ampdist: UGenRecursiveInput = ..., durdist: UGenRecursiveInput = ..., adparam: UGenRecursiveInput = ..., ddparam: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., ampscale: UGenRecursiveInput = ..., durscale: UGenRecursiveInput = ..., init_cps: UGenRecursiveInput = ..., knum: UGenRecursiveInput = ...) -> UGenOperable: ...
