from typing import Any

from ..typing import CalculationRateLike
from .core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, param, ugen

class GrainBuf(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, trigger: UGenScalarInput = ..., duration: UGenScalarInput = ..., buffer_id: UGenScalarInput = ..., rate: UGenScalarInput = ..., position: UGenScalarInput = ..., interpolate: UGenScalarInput = ..., pan: UGenScalarInput = ..., envelope_buffer_id: UGenScalarInput = ..., maximum_overlap: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def rate(self) -> UGenScalar: ...
    @property
    def position(self) -> UGenScalar: ...
    @property
    def interpolate(self) -> UGenScalar: ...
    @property
    def pan(self) -> UGenScalar: ...
    @property
    def envelope_buffer_id(self) -> UGenScalar: ...
    @property
    def maximum_overlap(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., buffer_id: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., interpolate: UGenRecursiveInput = ..., pan: UGenRecursiveInput = ..., envelope_buffer_id: UGenRecursiveInput = ..., maximum_overlap: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class GrainIn(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, trigger: UGenScalarInput = ..., duration: UGenScalarInput = ..., source: UGenScalarInput = ..., position: UGenScalarInput = ..., envelope_buffer_id: UGenScalarInput = ..., maximum_overlap: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def position(self) -> UGenScalar: ...
    @property
    def envelope_buffer_id(self) -> UGenScalar: ...
    @property
    def maximum_overlap(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., envelope_buffer_id: UGenRecursiveInput = ..., maximum_overlap: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class PitchShift(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., window_size: UGenScalarInput = ..., pitch_ratio: UGenScalarInput = ..., pitch_dispersion: UGenScalarInput = ..., time_dispersion: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def window_size(self) -> UGenScalar: ...
    @property
    def pitch_ratio(self) -> UGenScalar: ...
    @property
    def pitch_dispersion(self) -> UGenScalar: ...
    @property
    def time_dispersion(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., window_size: UGenRecursiveInput = ..., pitch_ratio: UGenRecursiveInput = ..., pitch_dispersion: UGenRecursiveInput = ..., time_dispersion: UGenRecursiveInput = ...) -> UGenOperable: ...

class Warp1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, buffer_id: UGenScalarInput = ..., pointer: UGenScalarInput = ..., frequency_scaling: UGenScalarInput = ..., window_size: UGenScalarInput = ..., envelope_buffer_id: UGenScalarInput = ..., overlaps: UGenScalarInput = ..., window_rand_ratio: UGenScalarInput = ..., interpolation: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def pointer(self) -> UGenScalar: ...
    @property
    def frequency_scaling(self) -> UGenScalar: ...
    @property
    def window_size(self) -> UGenScalar: ...
    @property
    def envelope_buffer_id(self) -> UGenScalar: ...
    @property
    def overlaps(self) -> UGenScalar: ...
    @property
    def window_rand_ratio(self) -> UGenScalar: ...
    @property
    def interpolation(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., pointer: UGenRecursiveInput = ..., frequency_scaling: UGenRecursiveInput = ..., window_size: UGenRecursiveInput = ..., envelope_buffer_id: UGenRecursiveInput = ..., overlaps: UGenRecursiveInput = ..., window_rand_ratio: UGenRecursiveInput = ..., interpolation: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
