from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class FreqShift(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., frequency: UGenScalarInput = ..., phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class Hilbert(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class HilbertFIR(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
