from .core import UGenScalar, ugen, UGenScalarInput, param, UGenOperable, UGenRecursiveInput, UGen
from ..typing import CalculationRateLike
from typing import Any
class BlockSize(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class BufChannels(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufDur(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufFrames(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufRateScale(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufSampleRate(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class BufSamples(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, buffer_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class ControlDur(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class ControlRate(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NodeID(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NumAudioBuses(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NumBuffers(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NumControlBuses(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NumInputBuses(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NumOutputBuses(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class NumRunningSynths(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def kr(cls) -> UGenOperable: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class RadiansPerSample(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class SampleDur(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class SampleRate(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...

class SubsampleOffset(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ir(cls) -> UGenOperable: ...
