from typing import Any, Sequence

from ..enums import CalculationRate
from ..typing import CalculationRateLike
from ..utils import repeat_to_length
from .core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput, param, ugen

class In(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, bus: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, bus: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, bus: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class InFeedback(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, bus: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, bus: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, bus: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class LocalIn(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, default: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def default(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, default: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, default: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class LocalOut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class OffsetOut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, bus: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, bus: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, bus: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class Out(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, bus: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, bus: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, bus: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class ReplaceOut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, bus: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, bus: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, bus: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class XOut(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, bus: UGenScalarInput = ..., crossfade: UGenScalarInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus(self) -> UGenScalar: ...
    @property
    def crossfade(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, bus: UGenRecursiveInput = ..., crossfade: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, bus: UGenRecursiveInput = ..., crossfade: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
