from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class LinLin(PseudoUGen):
    @staticmethod
    def ar(source, input_minimum = 0.0, input_maximum = 1.0, output_minimum = 1.0, output_maximum = 2.0) -> UGenOperable: ...
    @staticmethod
    def kr(source, input_minimum = 0.0, input_maximum = 1.0, output_minimum = 1.0, output_maximum = 2.0) -> UGenOperable: ...

class Silence(PseudoUGen):
    @classmethod
    def ar(cls, channel_count = 1) -> Any: ...

class A2K(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class AmpComp(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., root: UGenScalarInput = ..., exp: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def root(self) -> UGenScalar: ...
    @property
    def exp(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., root: UGenRecursiveInput = ..., exp: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., root: UGenRecursiveInput = ..., exp: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, frequency: UGenRecursiveInput = ..., root: UGenRecursiveInput = ..., exp: UGenRecursiveInput = ...) -> UGenOperable: ...

class AmpCompA(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., root: UGenScalarInput = ..., min_amp: UGenScalarInput = ..., root_amp: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def root(self) -> UGenScalar: ...
    @property
    def min_amp(self) -> UGenScalar: ...
    @property
    def root_amp(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., root: UGenRecursiveInput = ..., min_amp: UGenRecursiveInput = ..., root_amp: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., root: UGenRecursiveInput = ..., min_amp: UGenRecursiveInput = ..., root_amp: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, frequency: UGenRecursiveInput = ..., root: UGenRecursiveInput = ..., min_amp: UGenRecursiveInput = ..., root_amp: UGenRecursiveInput = ...) -> UGenOperable: ...

class DC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class K2A(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class LinExp(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., input_minimum: UGenScalarInput = ..., input_maximum: UGenScalarInput = ..., output_minimum: UGenScalarInput = ..., output_maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def input_minimum(self) -> UGenScalar: ...
    @property
    def input_maximum(self) -> UGenScalar: ...
    @property
    def output_minimum(self) -> UGenScalar: ...
    @property
    def output_maximum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., input_minimum: UGenRecursiveInput = ..., input_maximum: UGenRecursiveInput = ..., output_minimum: UGenRecursiveInput = ..., output_maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., input_minimum: UGenRecursiveInput = ..., input_maximum: UGenRecursiveInput = ..., output_minimum: UGenRecursiveInput = ..., output_maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class Line(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, start: UGenScalarInput = ..., stop: UGenScalarInput = ..., duration: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def start(self) -> UGenScalar: ...
    @property
    def stop(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, start: UGenRecursiveInput = ..., stop: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, start: UGenRecursiveInput = ..., stop: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class XLine(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, start: UGenScalarInput = ..., stop: UGenScalarInput = ..., duration: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def start(self) -> UGenScalar: ...
    @property
    def stop(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, start: UGenRecursiveInput = ..., stop: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, start: UGenRecursiveInput = ..., stop: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
