from ..enums import SignalRange
from .core import UGenScalar, UGenScalarInput, ugen, param, UGenOperable, UGenRecursiveInput, UGen
from ..typing import CalculationRateLike
from typing import Any
class KeyState(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, keycode: UGenScalarInput = ..., minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., lag: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def keycode(self) -> UGenScalar: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def lag(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, keycode: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., lag: UGenRecursiveInput = ...) -> UGenOperable: ...

class MouseButton(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., lag: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def lag(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., lag: UGenRecursiveInput = ...) -> UGenOperable: ...

class MouseX(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., warp: UGenScalarInput = ..., lag: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def warp(self) -> UGenScalar: ...
    @property
    def lag(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., warp: UGenRecursiveInput = ..., lag: UGenRecursiveInput = ...) -> UGenOperable: ...

class MouseY(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., warp: UGenScalarInput = ..., lag: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def warp(self) -> UGenScalar: ...
    @property
    def lag(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., warp: UGenRecursiveInput = ..., lag: UGenRecursiveInput = ...) -> UGenOperable: ...
