from typing import Any
from uqbar.enums import IntEnumeration
from ..enums import CalculationRate
from .core import UGenScalar, UGenScalarInput, ugen, param, UGenOperable, UGenRecursiveInput, UGen
from ..typing import CalculationRateLike
class ODFType(IntEnumeration):
    ...

class BeatTrack(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., lock: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def lock(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., lock: UGenRecursiveInput = ...) -> UGenOperable: ...

class BeatTrack2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, bus_index: UGenScalarInput = ..., feature_count: UGenScalarInput = ..., window_size: UGenScalarInput = ..., phase_accuracy: UGenScalarInput = ..., lock: UGenScalarInput = ..., weighting_scheme: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def bus_index(self) -> UGenScalar: ...
    @property
    def feature_count(self) -> UGenScalar: ...
    @property
    def window_size(self) -> UGenScalar: ...
    @property
    def phase_accuracy(self) -> UGenScalar: ...
    @property
    def lock(self) -> UGenScalar: ...
    @property
    def weighting_scheme(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, bus_index: UGenRecursiveInput = ..., feature_count: UGenRecursiveInput = ..., window_size: UGenRecursiveInput = ..., phase_accuracy: UGenRecursiveInput = ..., lock: UGenRecursiveInput = ..., weighting_scheme: UGenRecursiveInput = ...) -> UGenOperable: ...

class KeyTrack(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., key_decay: UGenScalarInput = ..., chroma_leak: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def key_decay(self) -> UGenScalar: ...
    @property
    def chroma_leak(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., key_decay: UGenRecursiveInput = ..., chroma_leak: UGenRecursiveInput = ...) -> UGenOperable: ...

class Loudness(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., smask: UGenScalarInput = ..., tmask: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def smask(self) -> UGenScalar: ...
    @property
    def tmask(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., smask: UGenRecursiveInput = ..., tmask: UGenRecursiveInput = ...) -> UGenOperable: ...

class MFCC(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., coeff_count: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def coeff_count(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., coeff_count: UGenRecursiveInput = ...) -> UGenOperable: ...

class Onsets(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., threshold: UGenScalarInput = ..., odftype: UGenScalarInput = ..., relaxtime: UGenScalarInput = ..., floor_: UGenScalarInput = ..., mingap: UGenScalarInput = ..., medianspan: UGenScalarInput = ..., whtype: UGenScalarInput = ..., rawodf: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @property
    def odftype(self) -> UGenScalar: ...
    @property
    def relaxtime(self) -> UGenScalar: ...
    @property
    def floor_(self) -> UGenScalar: ...
    @property
    def mingap(self) -> UGenScalar: ...
    @property
    def medianspan(self) -> UGenScalar: ...
    @property
    def whtype(self) -> UGenScalar: ...
    @property
    def rawodf(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ..., odftype: UGenRecursiveInput = ..., relaxtime: UGenRecursiveInput = ..., floor_: UGenRecursiveInput = ..., mingap: UGenRecursiveInput = ..., medianspan: UGenRecursiveInput = ..., whtype: UGenRecursiveInput = ..., rawodf: UGenRecursiveInput = ...) -> UGenOperable: ...

class Pitch(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., initial_frequency: UGenScalarInput = ..., min_frequency: UGenScalarInput = ..., max_frequency: UGenScalarInput = ..., exec_frequency: UGenScalarInput = ..., max_bins_per_octave: UGenScalarInput = ..., median: UGenScalarInput = ..., amplitude_threshold: UGenScalarInput = ..., peak_threshold: UGenScalarInput = ..., down_sample_factor: UGenScalarInput = ..., clarity: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def initial_frequency(self) -> UGenScalar: ...
    @property
    def min_frequency(self) -> UGenScalar: ...
    @property
    def max_frequency(self) -> UGenScalar: ...
    @property
    def exec_frequency(self) -> UGenScalar: ...
    @property
    def max_bins_per_octave(self) -> UGenScalar: ...
    @property
    def median(self) -> UGenScalar: ...
    @property
    def amplitude_threshold(self) -> UGenScalar: ...
    @property
    def peak_threshold(self) -> UGenScalar: ...
    @property
    def down_sample_factor(self) -> UGenScalar: ...
    @property
    def clarity(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., initial_frequency: UGenRecursiveInput = ..., min_frequency: UGenRecursiveInput = ..., max_frequency: UGenRecursiveInput = ..., exec_frequency: UGenRecursiveInput = ..., max_bins_per_octave: UGenRecursiveInput = ..., median: UGenRecursiveInput = ..., amplitude_threshold: UGenRecursiveInput = ..., peak_threshold: UGenRecursiveInput = ..., down_sample_factor: UGenRecursiveInput = ..., clarity: UGenRecursiveInput = ...) -> UGenOperable: ...

class SpecCentroid(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class SpecFlatness(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class SpecPcile(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., fraction: UGenScalarInput = ..., interpolate: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def fraction(self) -> UGenScalar: ...
    @property
    def interpolate(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., fraction: UGenRecursiveInput = ..., interpolate: UGenRecursiveInput = ...) -> UGenOperable: ...
