from typing import Any, Sequence

from supriya.enums import EnvelopeShape
from supriya.typing import CalculationRateLike
from supriya.ugens.core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class BrownNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ar(cls) -> UGenOperable: ...
    @classmethod
    def kr(cls) -> UGenOperable: ...

class ClipNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ar(cls) -> UGenOperable: ...
    @classmethod
    def kr(cls) -> UGenOperable: ...

class CoinGate(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, probability: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def probability(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, probability: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, probability: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class Crackle(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, chaos_parameter: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def chaos_parameter(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, chaos_parameter: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, chaos_parameter: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dust(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, density: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def density(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, density: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, density: UGenRecursiveInput = ...) -> UGenOperable: ...

class Dust2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, density: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def density(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, density: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, density: UGenRecursiveInput = ...) -> UGenOperable: ...

class ExpRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class GrayNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ar(cls) -> UGenOperable: ...
    @classmethod
    def kr(cls) -> UGenOperable: ...

class Hasher(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...

class IRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFClipNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFDClipNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFDNoise0(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFDNoise1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFDNoise3(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFNoise0(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFNoise1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFNoise2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class LinRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., skew: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def skew(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., skew: UGenRecursiveInput = ...) -> UGenOperable: ...

class Logistic(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, chaos_parameter: UGenScalarInput = ..., frequency: UGenScalarInput = ..., initial_y: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def chaos_parameter(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_y(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, chaos_parameter: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., initial_y: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, chaos_parameter: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., initial_y: UGenRecursiveInput = ...) -> UGenOperable: ...

class MantissaMask(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., bits: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def bits(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., bits: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., bits: UGenRecursiveInput = ...) -> UGenOperable: ...

class NRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., n: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def n(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., n: UGenRecursiveInput = ...) -> UGenOperable: ...

class PinkNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ar(cls) -> UGenOperable: ...
    @classmethod
    def kr(cls) -> UGenOperable: ...

class Rand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ir(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class RandID(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, rand_id: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def rand_id(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, rand_id: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, rand_id: UGenRecursiveInput = ...) -> UGenOperable: ...

class RandSeed(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., seed: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def seed(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., seed: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., seed: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, trigger: UGenRecursiveInput = ..., seed: UGenRecursiveInput = ...) -> UGenOperable: ...

class TExpRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class TIRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class TRand(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class TWindex(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., normalize: UGenScalarInput = ..., array: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def normalize(self) -> UGenScalar: ...
    @property
    def array(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., normalize: UGenRecursiveInput = ..., array: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., normalize: UGenRecursiveInput = ..., array: UGenRecursiveInput = ...) -> UGenOperable: ...

class WhiteNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...
    @classmethod
    def ar(cls) -> UGenOperable: ...
    @classmethod
    def kr(cls) -> UGenOperable: ...
