from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class COsc(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., frequency: UGenScalarInput = ..., beats: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def beats(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., beats: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., beats: UGenRecursiveInput = ...) -> UGenOperable: ...

class DegreeToKey(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., octave: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def octave(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., octave: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., octave: UGenRecursiveInput = ...) -> UGenOperable: ...

class Impulse(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class Index(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFCub(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFGauss(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, duration: UGenScalarInput = ..., width: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., loop: UGenScalarInput = ..., done_action: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def duration(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @property
    def loop(self) -> UGenScalar: ...
    @property
    def done_action(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, duration: UGenRecursiveInput = ..., width: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, duration: UGenRecursiveInput = ..., width: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ..., loop: UGenRecursiveInput = ..., done_action: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFPar(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFPulse(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., width: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFSaw(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class LFTri(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class Osc(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class OscN(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class Select(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, selector: UGenScalarInput = ..., sources: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def selector(self) -> UGenScalar: ...
    @property
    def sources(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, selector: UGenRecursiveInput = ..., sources: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, selector: UGenRecursiveInput = ..., sources: UGenRecursiveInput = ...) -> UGenOperable: ...

class SinOsc(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class SyncSaw(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, sync_frequency: UGenScalarInput = ..., saw_frequency: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def sync_frequency(self) -> UGenScalar: ...
    @property
    def saw_frequency(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, sync_frequency: UGenRecursiveInput = ..., saw_frequency: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, sync_frequency: UGenRecursiveInput = ..., saw_frequency: UGenRecursiveInput = ...) -> UGenOperable: ...

class VOsc(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., frequency: UGenScalarInput = ..., phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., frequency: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class VOsc3(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., freq_1: UGenScalarInput = ..., freq_2: UGenScalarInput = ..., freq_3: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def freq_1(self) -> UGenScalar: ...
    @property
    def freq_2(self) -> UGenScalar: ...
    @property
    def freq_3(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., freq_1: UGenRecursiveInput = ..., freq_2: UGenRecursiveInput = ..., freq_3: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., freq_1: UGenRecursiveInput = ..., freq_2: UGenRecursiveInput = ..., freq_3: UGenRecursiveInput = ...) -> UGenOperable: ...

class VarSaw(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., width: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...

class Vibrato(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, frequency: UGenScalarInput = ..., rate: UGenScalarInput = ..., depth: UGenScalarInput = ..., delay: UGenScalarInput = ..., onset: UGenScalarInput = ..., rate_variation: UGenScalarInput = ..., depth_variation: UGenScalarInput = ..., initial_phase: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def frequency(self) -> UGenScalar: ...
    @property
    def rate(self) -> UGenScalar: ...
    @property
    def depth(self) -> UGenScalar: ...
    @property
    def delay(self) -> UGenScalar: ...
    @property
    def onset(self) -> UGenScalar: ...
    @property
    def rate_variation(self) -> UGenScalar: ...
    @property
    def depth_variation(self) -> UGenScalar: ...
    @property
    def initial_phase(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, frequency: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., depth: UGenRecursiveInput = ..., delay: UGenRecursiveInput = ..., onset: UGenRecursiveInput = ..., rate_variation: UGenRecursiveInput = ..., depth_variation: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, frequency: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., depth: UGenRecursiveInput = ..., delay: UGenRecursiveInput = ..., onset: UGenRecursiveInput = ..., rate_variation: UGenRecursiveInput = ..., depth_variation: UGenRecursiveInput = ..., initial_phase: UGenRecursiveInput = ...) -> UGenOperable: ...

class WrapIndex(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
