from typing import Any

from ..enums import CalculationRate
from ..typing import CalculationRateLike
from .basic import Mix
from .core import PseudoUGen, UGen, UGenOperable, UGenRecursiveInput, UGenRecursiveParams, UGenScalar, UGenScalarInput, UGenVector, _get_method_for_rate, param, ugen

class Splay(PseudoUGen):
    @classmethod
    def ar(cls, source, center = 0, level = 1, normalize = True, spread = 1) -> Any: ...
    @classmethod
    def kr(cls, source, center = 0, level = 1, normalize = True, spread = 1) -> Any: ...

class Balance2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, left: UGenScalarInput = ..., right: UGenScalarInput = ..., position: UGenScalarInput = ..., level: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def left(self) -> UGenScalar: ...
    @property
    def right(self) -> UGenScalar: ...
    @property
    def position(self) -> UGenScalar: ...
    @property
    def level(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, left: UGenRecursiveInput = ..., right: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., level: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, left: UGenRecursiveInput = ..., right: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., level: UGenRecursiveInput = ...) -> UGenOperable: ...

class BiPanB2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, in_a: UGenScalarInput = ..., in_b: UGenScalarInput = ..., azimuth: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def in_a(self) -> UGenScalar: ...
    @property
    def in_b(self) -> UGenScalar: ...
    @property
    def azimuth(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, in_a: UGenRecursiveInput = ..., in_b: UGenRecursiveInput = ..., azimuth: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, in_a: UGenRecursiveInput = ..., in_b: UGenRecursiveInput = ..., azimuth: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...

class DecodeB2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 4, w: UGenScalarInput = ..., x: UGenScalarInput = ..., y: UGenScalarInput = ..., orientation: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def w(self) -> UGenScalar: ...
    @property
    def x(self) -> UGenScalar: ...
    @property
    def y(self) -> UGenScalar: ...
    @property
    def orientation(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, w: UGenRecursiveInput = ..., x: UGenRecursiveInput = ..., y: UGenRecursiveInput = ..., orientation: UGenRecursiveInput = ..., channel_count: int = 4) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, w: UGenRecursiveInput = ..., x: UGenRecursiveInput = ..., y: UGenRecursiveInput = ..., orientation: UGenRecursiveInput = ..., channel_count: int = 4) -> UGenOperable: ...

class Pan2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., position: UGenScalarInput = ..., level: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def position(self) -> UGenScalar: ...
    @property
    def level(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., level: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., level: UGenRecursiveInput = ...) -> UGenOperable: ...

class Pan4(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., x_position: UGenScalarInput = ..., y_position: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def x_position(self) -> UGenScalar: ...
    @property
    def y_position(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., x_position: UGenRecursiveInput = ..., y_position: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., x_position: UGenRecursiveInput = ..., y_position: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PanAz(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, channel_count: int = 1, source: UGenScalarInput = ..., position: UGenScalarInput = ..., amplitude: UGenScalarInput = ..., width: UGenScalarInput = ..., orientation: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def position(self) -> UGenScalar: ...
    @property
    def amplitude(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @property
    def orientation(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., amplitude: UGenRecursiveInput = ..., width: UGenRecursiveInput = ..., orientation: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., position: UGenRecursiveInput = ..., amplitude: UGenRecursiveInput = ..., width: UGenRecursiveInput = ..., orientation: UGenRecursiveInput = ..., channel_count: int = 1) -> UGenOperable: ...

class PanB(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., azimuth: UGenScalarInput = ..., elevation: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def azimuth(self) -> UGenScalar: ...
    @property
    def elevation(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., azimuth: UGenRecursiveInput = ..., elevation: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., azimuth: UGenRecursiveInput = ..., elevation: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PanB2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., azimuth: UGenScalarInput = ..., gain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def azimuth(self) -> UGenScalar: ...
    @property
    def gain(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., azimuth: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., azimuth: UGenRecursiveInput = ..., gain: UGenRecursiveInput = ...) -> UGenOperable: ...

class Rotate2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, x: UGenScalarInput = ..., y: UGenScalarInput = ..., position: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def x(self) -> UGenScalar: ...
    @property
    def y(self) -> UGenScalar: ...
    @property
    def position(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, x: UGenRecursiveInput = ..., y: UGenRecursiveInput = ..., position: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, x: UGenRecursiveInput = ..., y: UGenRecursiveInput = ..., position: UGenRecursiveInput = ...) -> UGenOperable: ...

class XFade2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, in_a: UGenScalarInput = ..., in_b: UGenScalarInput = ..., pan: UGenScalarInput = ..., level: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def in_a(self) -> UGenScalar: ...
    @property
    def in_b(self) -> UGenScalar: ...
    @property
    def pan(self) -> UGenScalar: ...
    @property
    def level(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, in_a: UGenRecursiveInput = ..., in_b: UGenRecursiveInput = ..., pan: UGenRecursiveInput = ..., level: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, in_a: UGenRecursiveInput = ..., in_b: UGenRecursiveInput = ..., pan: UGenRecursiveInput = ..., level: UGenRecursiveInput = ...) -> UGenOperable: ...
