from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Ball(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., gravity: UGenScalarInput = ..., damping: UGenScalarInput = ..., friction: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def gravity(self) -> UGenScalar: ...
    @property
    def damping(self) -> UGenScalar: ...
    @property
    def friction(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., gravity: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ..., friction: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., gravity: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ..., friction: UGenRecursiveInput = ...) -> UGenOperable: ...

class Pluck(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., trigger: UGenScalarInput = ..., maximum_delay_time: UGenScalarInput = ..., delay_time: UGenScalarInput = ..., decay_time: UGenScalarInput = ..., coefficient: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def maximum_delay_time(self) -> UGenScalar: ...
    @property
    def delay_time(self) -> UGenScalar: ...
    @property
    def decay_time(self) -> UGenScalar: ...
    @property
    def coefficient(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ..., maximum_delay_time: UGenRecursiveInput = ..., delay_time: UGenRecursiveInput = ..., decay_time: UGenRecursiveInput = ..., coefficient: UGenRecursiveInput = ...) -> UGenOperable: ...

class Spring(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., spring: UGenScalarInput = ..., damping: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def spring(self) -> UGenScalar: ...
    @property
    def damping(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., spring: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., spring: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ...) -> UGenOperable: ...

class TBall(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., gravity: UGenScalarInput = ..., damping: UGenScalarInput = ..., friction: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def gravity(self) -> UGenScalar: ...
    @property
    def damping(self) -> UGenScalar: ...
    @property
    def friction(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., gravity: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ..., friction: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., gravity: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ..., friction: UGenRecursiveInput = ...) -> UGenOperable: ...
