from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class PV_ChainUGen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, **kwargs: Any) -> None: ...

class FFT(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, buffer_id: UGenScalarInput = ..., source: UGenScalarInput = ..., hop: UGenScalarInput = ..., window_type: UGenScalarInput = ..., active: UGenScalarInput = ..., window_size: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def buffer_id(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def hop(self) -> UGenScalar: ...
    @property
    def window_type(self) -> UGenScalar: ...
    @property
    def active(self) -> UGenScalar: ...
    @property
    def window_size(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, buffer_id: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., hop: UGenRecursiveInput = ..., window_type: UGenRecursiveInput = ..., active: UGenRecursiveInput = ..., window_size: UGenRecursiveInput = ...) -> UGenOperable: ...

class IFFT(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., window_type: UGenScalarInput = ..., window_size: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def window_type(self) -> UGenScalar: ...
    @property
    def window_size(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, pv_chain: UGenRecursiveInput = ..., window_type: UGenRecursiveInput = ..., window_size: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., window_type: UGenRecursiveInput = ..., window_size: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Add(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_BinScramble(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., wipe: UGenScalarInput = ..., width: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def wipe(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., wipe: UGenRecursiveInput = ..., width: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_BinShift(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., stretch: UGenScalarInput = ..., shift: UGenScalarInput = ..., interpolate: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def stretch(self) -> UGenScalar: ...
    @property
    def shift(self) -> UGenScalar: ...
    @property
    def interpolate(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., stretch: UGenRecursiveInput = ..., shift: UGenRecursiveInput = ..., interpolate: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_BinWipe(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., wipe: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @property
    def wipe(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ..., wipe: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_BrickWall(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., wipe: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def wipe(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., wipe: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_ConformalMap(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., areal: UGenScalarInput = ..., aimag: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def areal(self) -> UGenScalar: ...
    @property
    def aimag(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., areal: UGenRecursiveInput = ..., aimag: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Conj(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Copy(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_CopyPhase(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Diffuser(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Div(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_HainsworthFoote(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., proph: UGenScalarInput = ..., propf: UGenScalarInput = ..., threshold: UGenScalarInput = ..., waittime: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def proph(self) -> UGenScalar: ...
    @property
    def propf(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @property
    def waittime(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., proph: UGenRecursiveInput = ..., propf: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ..., waittime: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_JensenAndersen(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., propsc: UGenScalarInput = ..., prophfe: UGenScalarInput = ..., prophfc: UGenScalarInput = ..., propsf: UGenScalarInput = ..., threshold: UGenScalarInput = ..., waittime: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def propsc(self) -> UGenScalar: ...
    @property
    def prophfe(self) -> UGenScalar: ...
    @property
    def prophfc(self) -> UGenScalar: ...
    @property
    def propsf(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @property
    def waittime(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., propsc: UGenRecursiveInput = ..., prophfe: UGenRecursiveInput = ..., prophfc: UGenRecursiveInput = ..., propsf: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ..., waittime: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_LocalMax(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., threshold: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagAbove(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., threshold: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagBelow(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., threshold: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagClip(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., threshold: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def threshold(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., threshold: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagDiv(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., zeroed: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @property
    def zeroed(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ..., zeroed: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagFreeze(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., freeze: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def freeze(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., freeze: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagMul(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagNoise(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagShift(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., stretch: UGenScalarInput = ..., shift: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def stretch(self) -> UGenScalar: ...
    @property
    def shift(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., stretch: UGenRecursiveInput = ..., shift: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagSmear(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., bins: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def bins(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., bins: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_MagSquared(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Max(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Min(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_Mul(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_PhaseShift(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., shift: UGenScalarInput = ..., integrate: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def shift(self) -> UGenScalar: ...
    @property
    def integrate(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., shift: UGenRecursiveInput = ..., integrate: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_PhaseShift270(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_PhaseShift90(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_RandComb(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., wipe: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def wipe(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., wipe: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_RandWipe(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., wipe: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @property
    def wipe(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ..., wipe: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_RectComb(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain: UGenScalarInput = ..., num_teeth: UGenScalarInput = ..., phase: UGenScalarInput = ..., width: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain(self) -> UGenScalar: ...
    @property
    def num_teeth(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain: UGenRecursiveInput = ..., num_teeth: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...

class PV_RectComb2(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, pv_chain_a: UGenScalarInput = ..., pv_chain_b: UGenScalarInput = ..., num_teeth: UGenScalarInput = ..., phase: UGenScalarInput = ..., width: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def pv_chain_a(self) -> UGenScalar: ...
    @property
    def pv_chain_b(self) -> UGenScalar: ...
    @property
    def num_teeth(self) -> UGenScalar: ...
    @property
    def phase(self) -> UGenScalar: ...
    @property
    def width(self) -> UGenScalar: ...
    @classmethod
    def kr(cls, *, pv_chain_a: UGenRecursiveInput = ..., pv_chain_b: UGenRecursiveInput = ..., num_teeth: UGenRecursiveInput = ..., phase: UGenRecursiveInput = ..., width: UGenRecursiveInput = ...) -> UGenOperable: ...

class RunningSum(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., sample_count: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def sample_count(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., sample_count: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., sample_count: UGenRecursiveInput = ...) -> UGenOperable: ...
