from .core import UGenScalar, UGenScalarInput, ugen, param, UGenOperable, UGenRecursiveInput, UGen
from ..typing import CalculationRateLike
from typing import Any
class FreeVerb(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., mix: UGenScalarInput = ..., room_size: UGenScalarInput = ..., damping: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def mix(self) -> UGenScalar: ...
    @property
    def room_size(self) -> UGenScalar: ...
    @property
    def damping(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., mix: UGenRecursiveInput = ..., room_size: UGenRecursiveInput = ..., damping: UGenRecursiveInput = ...) -> UGenOperable: ...
