from typing import Any
from ..enums import CalculationRate
from .core import UGenScalar, UGenScalarInput, ugen, param, UGenOperable, UGenRecursiveInput, UGen
from ..typing import CalculationRateLike
class CheckBadValues(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., ugen_id: UGenScalarInput = ..., post_mode: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def ugen_id(self) -> UGenScalar: ...
    @property
    def post_mode(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., ugen_id: UGenRecursiveInput = ..., post_mode: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., ugen_id: UGenRecursiveInput = ..., post_mode: UGenRecursiveInput = ...) -> UGenOperable: ...

class Sanitize(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., replace: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def replace(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., replace: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., replace: UGenRecursiveInput = ...) -> UGenOperable: ...
