from typing import Any

from supriya.typing import CalculationRateLike
from supriya.ugens.core import UGen, UGenOperable, UGenRecursiveInput, UGenScalar, UGenScalarInput, UGenVector, UGenVectorInput

class Clip(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class Fold(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class Gate(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class InRange(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class Latch(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class LeastChange(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, a: UGenScalarInput = ..., b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ...) -> UGenOperable: ...

class MostChange(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, a: UGenScalarInput = ..., b: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def a(self) -> UGenScalar: ...
    @property
    def b(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, a: UGenRecursiveInput = ..., b: UGenRecursiveInput = ...) -> UGenOperable: ...

class Peak(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class PeakFollower(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., decay: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def decay(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., decay: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., decay: UGenRecursiveInput = ...) -> UGenOperable: ...

class Phasor(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., rate: UGenScalarInput = ..., start: UGenScalarInput = ..., stop: UGenScalarInput = ..., reset_pos: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def rate(self) -> UGenScalar: ...
    @property
    def start(self) -> UGenScalar: ...
    @property
    def stop(self) -> UGenScalar: ...
    @property
    def reset_pos(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., start: UGenRecursiveInput = ..., stop: UGenRecursiveInput = ..., reset_pos: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ..., start: UGenRecursiveInput = ..., stop: UGenRecursiveInput = ..., reset_pos: UGenRecursiveInput = ...) -> UGenOperable: ...

class Poll(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., source: UGenScalarInput = ..., trigger_id: UGenScalarInput = ..., label: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger_id(self) -> UGenScalar: ...
    @property
    def label(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., trigger_id: UGenRecursiveInput = ..., label: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., trigger_id: UGenRecursiveInput = ..., label: UGenRecursiveInput = ...) -> UGenOperable: ...

class RunningMax(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class RunningMin(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class Schmidt(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class SendPeakRMS(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, reply_rate: UGenScalarInput = ..., peak_lag: UGenScalarInput = ..., reply_id: UGenScalarInput = ..., source_size: UGenScalarInput = ..., source: UGenVectorInput = ..., character_count: UGenScalarInput = ..., character: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def reply_rate(self) -> UGenScalar: ...
    @property
    def peak_lag(self) -> UGenScalar: ...
    @property
    def reply_id(self) -> UGenScalar: ...
    @property
    def source_size(self) -> UGenScalar: ...
    @property
    def source(self) -> UGenVector: ...
    @property
    def character_count(self) -> UGenScalar: ...
    @property
    def character(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, reply_rate: UGenRecursiveInput = ..., peak_lag: UGenRecursiveInput = ..., reply_id: UGenRecursiveInput = ..., source_size: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., character_count: UGenRecursiveInput = ..., character: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, reply_rate: UGenRecursiveInput = ..., peak_lag: UGenRecursiveInput = ..., reply_id: UGenRecursiveInput = ..., source_size: UGenRecursiveInput = ..., source: UGenRecursiveInput = ..., character_count: UGenRecursiveInput = ..., character: UGenRecursiveInput = ...) -> UGenOperable: ...

class SendReply(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., reply_id: UGenScalarInput = ..., character_count: UGenScalarInput = ..., character: UGenVectorInput = ..., source: UGenVectorInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def reply_id(self) -> UGenScalar: ...
    @property
    def character_count(self) -> UGenScalar: ...
    @property
    def character(self) -> UGenVector: ...
    @property
    def source(self) -> UGenVector: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., reply_id: UGenRecursiveInput = ..., character_count: UGenRecursiveInput = ..., character: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., reply_id: UGenRecursiveInput = ..., character_count: UGenRecursiveInput = ..., character: UGenRecursiveInput = ..., source: UGenRecursiveInput = ...) -> UGenOperable: ...

class SendTrig(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., id_: UGenScalarInput = ..., value: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def id_(self) -> UGenScalar: ...
    @property
    def value(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., id_: UGenRecursiveInput = ..., value: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., id_: UGenRecursiveInput = ..., value: UGenRecursiveInput = ...) -> UGenOperable: ...

class Sweep(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., rate: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @property
    def rate(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ..., rate: UGenRecursiveInput = ...) -> UGenOperable: ...

class TDelay(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., duration: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...

class ToggleFF(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, trigger: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def trigger(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, trigger: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, trigger: UGenRecursiveInput = ...) -> UGenOperable: ...

class Trig1(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., duration: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...

class Trig(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., duration: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def duration(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., duration: UGenRecursiveInput = ...) -> UGenOperable: ...

class Wrap(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., minimum: UGenScalarInput = ..., maximum: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @property
    def minimum(self) -> UGenScalar: ...
    @property
    def maximum(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def ir(cls, *, source: UGenRecursiveInput = ..., minimum: UGenRecursiveInput = ..., maximum: UGenRecursiveInput = ...) -> UGenOperable: ...

class ZeroCrossing(UGen):
    def __init__(self, *, calculation_rate: CalculationRateLike, source: UGenScalarInput = ..., **kwargs: Any) -> None: ...
    @property
    def source(self) -> UGenScalar: ...
    @classmethod
    def ar(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
    @classmethod
    def kr(cls, *, source: UGenRecursiveInput = ...) -> UGenOperable: ...
